config/routes.rb
Treebook::Application.routes.draw do
  as :user do
    get '/register', to: 'devise/registrations#new',via: :get, as: :register
    get '/login', to: 'devise/sessions#new', via: :get, as: :login
    get '/logout', to: 'devise/sessions#destroy', via: :delete, as: :logout
  end

  devise_for :users, :skip => [:sessions]

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do 
      put :accept
      put :block
    end
  end

  resources :statuses, :path => "updates", :path_names => {:new => "create"}

  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.all
      render action: :show
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class="page-header">
  <h1><%= @user.full_name %></h1>
</div>

<% if signed_in? %>
<div class="friend-status">
  <% if @user != current_user %>
  	<% if current_user.friends.include?(@user) || current_user.pending_friends.include?(@user) %>
  		<%= link_to "Edit Friendship", edit_user_friendship_path(@user.id), class: 'btn' %>
  	<% else %>
		<%= link_to "Add Friend", new_user_friendship_path(friend_id: @user.profile_name), class: 'btn',
		                                                                data: { friend_id: @user.to_param }, id: 'add-friendship', data: { friend_id: @user.to_param } %>
    <% end %>
  <% end %>
</div>
<% end %>

<div class="row">
	<div class="span6">
		<% if @statuses %>
		  <% @statuses.each do |status| %>
		    <div class="well">
		      <%= status.content %>
		      <hr />
		      <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
		    </div>
		  <% end %>
		<% end %>
	</div>
	<div class="span3 well">
			<legend>User Favorites</legend>
				Favorite Film: <%= @user.favorite_film %><br>
				Favorite TV Show: <%= @user.favorite_tv_show %><br>
				Favorite Book: <%= @user.favorite_book %><br>
				Favorite Band: <%= @user.favorite_band %>

	</div>
</div>