config/routes.rb
Treebook::Application.routes.draw do
  as :user do
    get '/register', to: 'devise/registrations#new',via: :get, as: :register
    get '/login', to: 'devise/sessions#new', via: :get, as: :login
    get '/logout', to: 'devise/sessions#destroy', via: :delete, as: :logout
  end

  devise_for :users, :skip => [:sessions]

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do 
      put :accept
      put :block
    end
  end

  resources :statuses, :path => "updates", :path_names => {:new => "create"}

  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a href="#" class="brand"> Treebook</a>
				<ul class="nav">
					<li><%= link_to "All Statuses", feed_path %></li>
				</ul>
				<ul class="nav pull-right">
					<% if user_signed_in? %>
						<li><%= link_to 'Friends', user_friendships_path %></li>
						<li><%= link_to "Edit User", edit_user_registration_path %></li>
						<li><%= link_to "Log Out", logout_path %></li>
					<% else %>
						<li><%= link_to "Register", register_path %></li>
						<li><%= link_to "Log in", login_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
	<div class="container">
		<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %>">
				<button class="close" data-dismiss="alert">×</button>
				<%= message %>
			</div>
		<% end %>
			<div class="row">
				<div class="span2 bs-docs-sidebar">
					<ul class="nav nav-list bs-docs-sidenav affix">
							<% if user_signed_in? %>
								<li><%= link_to "View Feed", feed_path %></li>
								<li><%= link_to "Post a New Status", new_status_path %></li>
								<li><%= link_to "Edit User", edit_user_registration_path  %></li>
								<li><%= link_to "View Profile", profile_path(current_user.profile_name) %></li>
								<li><%= link_to 'Friends', user_friendships_path %></li>
								<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
							<% else %>
								<li><%= link_to "Register", register_path %></li>
								<li><%= link_to "Log In", login_path %></li>
							<% end %>
					</ul>
				</div>
				<div class="span10">
					<%= yield %>
				</div>
			</div>
	</div>
	
</body>
</html>